/*
 * LED_SYSTEM_interface.h
 *      Author: Ahmed Sayed
                , Abdallah MAgdy
 */

#ifndef HAL_HEAT_COOL_ELEMENTS_HEAT_COOL_ELEMENTS_PRIVATE_H_
#define HAL_HEAT_COOL_ELEMENTS_HEAT_COOL_ELEMENTS_PRIVATE_H_



#endif /* HAL_HEAT_COOL_ELEMENTS_HEAT_COOL_ELEMENTS_PRIVATE_H_ */
